### ISSUE TITLE
Arrow size not sizing correctly

### ISSUE THREAD

**Issue by sangbpark94** [bsidelinger912/react-tooltip-lite#51] opened 2019-07-03 14:57 UTC
After you set `arrowSize` to a smaller size, the arrow for direction up looks right, but the arrows for direction left, right and down don't look right.

**Comment by bsidelinger912** [comment] 2019-07-08 02:32
Hey @sangbpark94 I'm not able to reproduce your issue, a smaller arrow size works fine for all directions in my dev environment:
<img width="815" alt="Screen Shot 2019-07-07 at 7 28 46 PM" src="https://user-images.githubusercontent.com/1426212/60778915-af48fc00-a0ed-11e9-90c0-7e176abd9088.png">
Can you give me some detailed reproduction steps?  An easy way to show the issue would be to fork this pen: https://codepen.io/bsidelinger912/pen/WOdPNK.

**Comment by bsidelinger912** [comment] 2019-12-11 07:51
Closing as I don't have enough info, feel free to open another with detailed repro steps.

**Closed by bsidelinger912** 2019-12-11 07:51 UTC
